import type { Cocktail } from '@/types';

// All cocktail data is served from static JSON files in /public/data/
// These files are generated by the build script: npm run fetch-cocktails
// Data source: TheCocktailDB (licensed)

export async function fetchAllCocktails(): Promise<Cocktail[]> {
  const response = await fetch('/data/cocktails.json');
  if (!response.ok) {
    throw new Error('Failed to fetch cocktails data');
  }
  const data = await response.json();
  return data.cocktails;
}

export async function fetchAllIngredients(): Promise<string[]> {
  const response = await fetch('/data/ingredients.json');
  if (!response.ok) {
    throw new Error('Failed to fetch ingredients data');
  }
  const data = await response.json();
  return data.ingredients;
}
